Lucky::DynamicCompressionHandler.configure do |settings|
  settings.compress_server_generated_content = true
end

# This setting turns off the serving of pre-compressed assets, but they will still
# be generated by webpack. To disable this remove the compression-webpack-plugin
# in webpack.mix.js
Lucky::StaticCompressionHandler.configure do |settings|
  settings.serve_precompressed_assets = true
end
