#!/bin/bash

# Exit if any subcommand fails
set -e
set -o pipefail

indent() {
    while read LINE; do
        echo "  $LINE" || true
    done
}

if ! command -v yarn > /dev/null; then
    printf 'Yarn is not installed.\n'
    printf 'See https://yarnpkg.com/lang/en/docs/install/ for install instructions.\n'
    exit 1
fi

printf "\n▸ Installing node dependencies\n"
yarn install --no-progress | indent

printf "\n▸ Compiling assets\n"
yarn dev | indent

printf "\n▸ Installing shards\n"
shards install | indent

printf "\n✔ All done. Run 'up' to start the app\n"
