name: Lucky CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: "*"

jobs:
  check_format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v1
      - name: Format
        run: crystal tool format --check
  specs:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:0.34.0

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: "Install yarn"
      run: npm install -g yarn
    - name: Setup Lucky
      run: script/setup
    - name: Cache shards
      uses: actions/cache@v1
      with:
        path: lib
        key: ${{ runner.os }}-shards-${{ hashFiles('**/shard.lock') }}
        restore-keys: |
          ${{ runner.os }}-shards-
    - name: Cache Crystal
      uses: actions/cache@v1
      with:
        path: ~/.cache/crystal
        key: ${{ runner.os }}-crystal
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Run tests
      run: crystal spec
